version: "3.3"
services:
  postgres:
    image: postgres:12.3
    restart: unless-stopped
    volumes:
      - ./db.sql.gz:/docker-entrypoint-initdb.d/db.sql.gz
    environment:
      POSTGRES_PASSWORD: postgres

  js:
    build: ./fastify
    ports:
    - "3001:3001"
    depends_on:
      - postgres

  go:
    build: ./go
    ports:
    - "3002:3002"
    depends_on:
      - postgres
